#!/bin/bash

echo "=== Xcode 日志错误修复指南 ==="
echo ""
echo "这个错误不会影响应用运行，但会影响日志显示"
echo ""
echo "✅ 推荐解决方案："
echo ""
echo "1. 在 Xcode 中："
echo "   - 点击顶部 Scheme 选择器（App 旁边）"
echo "   - 选择 'Edit Scheme...'"
echo "   - 左侧选择 'Run'"
echo "   - 点击 'Arguments' 标签页"
echo "   - 在 'Environment Variables' 部分，点击 '+' 按钮"
echo "   - 添加："
echo "     Name: IDEPreferLogStreaming"
echo "     Value: YES"
echo "   - 点击 'Close' 保存"
echo ""
echo "2. 重新运行应用（Cmd+R）"
echo ""
echo "📋 详细步骤请查看：frontend/FIX_XCODE_LOGGING_ERROR.md"
echo ""
echo "💡 替代方案：使用设备控制台查看日志（不需要修改配置）"
echo "   - Xcode > Window > Devices and Simulators"
echo "   - 选择 iPhone > Open Console"
